application:
  title:  SDDC Prototype
---
spring:
  profiles.active: prod
---
spring:
  profiles: prod
spring.datasource:
  dataSourceClassName: org.postgresql.Driver
  url: "jdbc:postgresql://86.119.35.56:5432/sddc"
  databaseName:
  serverName: "sddc.silvn.com"
  username: "sddc"
  password: "sddc2015"
  cachePrepStmts: true
  prepStmtCacheSize: 250
  prepStmtCacheSqlLimit: 2048
  useServerPrepStmts: true
spring.jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  database: POSTGRESQL
  openInView: false
  show_sql: true
  generate-ddl: true
  hibernate:
     ddl-auto: update
     naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
spring.properties:
   hibernate.cache.use_second_level_cache: true
   hibernate.cache.use_query_cache: false
   hibernate.generate_statistics: false
   hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
---
spring:
  profiles: dev
spring.jpa:
    database: HSQL
