application:
  title:  SDDC Prototype

spring:
    datasource:
      dataSourceClassName: org.postgresql.Driver
      url: "jdbc:postgresql://ec2-54-195-252-202.eu-west-1.compute.amazonaws.com/depmrmqbk7l1u8"
      databaseName:
      serverName: "ec2-54-195-252-202.eu-west-1.compute.amazonaws.com"
      username: plnxbeeghwvqrn
      password: "LUqPsG1rxI6mNHh9PvolnICe-M"
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: POSTGRESQL
        openInView: false
        show_sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

